{% set name = "gwsurrogate" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c3a1b9616c95403c776260933d4599567e066080f8bd7db82b870f4d6f07452

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    - numpy
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - gsl
    - numpy
    - pip
    - python
    - setuptools
  run:
    - gsl
    - gwtools
    - h5py
    - {{ pin_compatible('numpy') }}
    - python
    - scikit-learn
    - scipy

test:
  requires:
    - pip
  imports:
    - gwsurrogate
  commands:
    # check metadata
    - python -m pip check gwsurrogate
    - python -m pip show gwsurrogate

about:
  home: https://github.com/sxs-collaboration/gwsurrogate
  dev_url: https://github.com/sxs-collaboration/gwsurrogate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An easy to use interface to gravitational wave surrogate models
  description: |
    GWSurrogate is an easy to use interface to gravitational wave surrogate
    models.

    Surrogates provide a fast and accurate evaluation mechanism for
    gravitational waveforms which would otherwise be found through solving
    differential equations. These equations must be solved in the 'building'
    phase, which was performed using other codes.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - sfield17
    - vijayvarma392
