{% set name = "gwsurrogate" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab5524e10536452092141c4143238ee21acceda427ac07d86c1c85a27fd754c2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - gsl
    - numpy
    - pip
    - python
    - setuptools
  run:
    - gsl
    - gwtools
    - h5py
    - {{ pin_compatible('numpy') }}
    - python
    - scikit-learn

test:
  imports:
    - gwsurrogate

about:
  home: https://github.com/sxs-collaboration/gwsurrogate
  dev_url: https://github.com/sxs-collaboration/gwsurrogate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An easy to use interface to gravitational wave surrogate models
  description: |
    GWSurrogate is an easy to use interface to gravitational wave surrogate
    models.

    Surrogates provide a fast and accurate evaluation mechanism for
    gravitational waveforms which would otherwise be found through solving
    differential equations. These equations must be solved in the 'building'
    phase, which was performed using other codes.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - sfield17
    - vijayvarma392
